.\" Written by Kurt Lust, kurt.lust@uantwerpen.be.
.TH man 1 "24 October 2018" "0.2" "vsc-vnc overview"
.SH NAME
vsc-vnc \- Easier starting of a VNC server. 
.SH DESCRIPTION
vsc-vnc was created to make starting VNC sessions easier on the clusters at
UAntwerpen. In its current incarnation, the functionality is very limited.

Commands:
.IP \[bu] 2 
vnc-xfce : Start the VNC server with with Xfce as the window manager/desktop (Xfce.org).

.P
Note that this module will only work on nodes that already have a VNC server
installed as the server is not part of the vsc-vnc tools.
.SH SEE ALSO
vnc-xfce(1)
.SH AUTHOR
Kurt Lust (Kurt.Lust@uantwerpen.be)